name: "Verify"
"on":
  workflow_dispatch:
jobs:
  verify:
    name: "Verify"
    runs-on: "ubuntu-latest"
    steps:
    - name: "Verify"
      id: "verify"
      shell: bash
      run: "echo '${{ GITHUB_RUN_ID }}'"
